#!/bin/bash

if [ "$EUID" -ne 0 ]; then
  printf '%s\n' 'error: scan needs root privilege'
  printf '%s\n' 'usage: '"$0"' <IP address> [IP address [IP ...]]'
  exit 0
fi

if [ "$#" -eq 0 ]; then
  printf '%s\n' 'usage: '"$0"' <IP address> [IP address [IP ...]]'
  exit 0
fi

com[0]='nmap "$ip" --top-ports 1000 -v2 -sS --open -oN "$nmapdir"/nmap-sS-top1000-"$(date | tr '"'"' '"'"' '"'"'-'"'"')".txt'
com[1]='nmap "$ip" --top-ports 30 -v2 -Pn -sU --open -oN "$nmapdir"/nmap-sU-top30-"$(date | tr '"'"' '"'"' '"'"'-'"'"')".txt'
com[2]='tcpopens="$(find "$nmapdir" ! -name '"'"'nmap-sU*'"'"' -type f -print0 | xargs -0 cat | grep -E '"'"'^[0-9]+/'"'"' | grep -oE '"'"'^[0-9]+'"'"' | sort -un | tr $'"'"'\n'"'"' , | sed '"'"'s/,$//'"'"')"'
com[3]='nmap "$ip" -p"$tcpopens" -v2 -Pn -sS -sV --open -oN "$nmapdir"/nmap-sV-top1000-"$(date | tr '"'"' '"'"' '"'"'-'"'"')".txt'
com[4]='nmap "$ip" -p"$tcpopens" -v2 -Pn -sS -A --open -oN "$nmapdir"/nmap-A-top1000-"$(date | tr '"'"' '"'"' '"'"'-'"'"')".txt'
com[5]='nmap "$ip" -p"$tcpopens" -v2 -Pn -sS -sV --open --script vuln -oN "$nmapdir"'"'"'/nmap-vuln-top1000-'"'"'"$(date | tr '"'"' '"'"' '"'"'-'"'"')".txt'
com[6]='nmap "$ip" -p- -v2 -sS --open -oN "$nmapdir"/nmap-sS-all-"$(date | tr '"'"' '"'"' '"'"'-'"'"')".txt'
com[7]='udpopens="$(cat "$nmapdir"/nmap-sU*.txt | grep -oE '"'"'^[0-9]+'"'"' | sort -u | tr '"'"'\n'"'"' '"'"','"'"' | sed '"'"'s/,$//'"'"')"'
com[8]='nmap "$ip" -p"$udpopens" -v2 -Pn -sU -A --open -oN "$nmapdir"/nmap-sU-A-"$(date | tr '"'"' '"'"' '"'"'-'"'"')".txt'
com[9]='nmap "$ip" -p"$udpopens" -v2 -Pn -sU -sV -script vuln --open -oN "$nmapdir"/nmap-sU-sV-vuln-"$(date | tr '"'"' '"'"' '"'"'-'"'"')".txt'
com[10]='nmap "$ip" -p- -v2 -Pn -sS --open -oN "$nmapdir"/nmap-sS-all2-"$(date | tr '"'"' '"'"' '"'"'-'"'"')".txt'
com[11]='nmap "$ip" -p- -v2 -Pn -sS --open -oN "$nmapdir"/nmap-sS-all3-"$(date | tr '"'"' '"'"' '"'"'-'"'"')".txt'
com[12]='tcpopens="$(find "$nmapdir" ! -name '"'"'nmap-sU*'"'"' -type f -print0 | xargs -0 cat | grep -E '"'"'^[0-9]+/'"'"' | grep -oE '"'"'^[0-9]+'"'"' | sort -un | tr $'"'"'\n'"'"' , | sed '"'"'s/,$//'"'"')"'
com[13]='nmap "$ip" -p"$tcpopens" -v2 -Pn -sS -A -oN "$nmapdir"/nmap-last-A-"$(date | tr '"'"' '"'"' '"'"'-'"'"')".txt'
com[14]='nmap "$ip" -p"$tcpopens" -v2 -Pn -sS -sV --script vuln -oN "$nmapdir"/nmap-last-vuln-"$(date | tr '"'"' '"'"' '"'"'-'"'"')".txt'
com[15]='nmap "$ip" --top-ports 100 -v2 -Pn -sU --open -oN "$nmapdir"/nmap-sU-top100-"$(date | tr '"'"' '"'"' '"'"'-'"'"')".txt'

# change this!
basedir='/mnt/hgfs/shared-kali'

for ip in "$@"; do
  mkdir -p "$basedir"'/'"$ip"'/nmap'
done

for command in "${com[@]}"; do
  for ip in "$@"; do
    nmapdir="$basedir"'/'"$ip"'/nmap'
    eval "$command"
  done
done
