#!/bin/bash

if [ "$#" -ne 1 ]; then
  printf '%s\n' 'usage: '"$0"' <sekurlsa::logonpasswords file>'
  exit 0
fi

cat "$1" | grep -E '\* (Username|Domain|NTLM|Password)' | sed 's/^ *\* //; s/ *: */:/' | \
  awk -F: '
    {
      if($2 == "(null)") {
        w = 0
      } else if($1 == "Username") {
        if($2 !~ /.*\$$/) {
          p = $2
          w = 1
        }
      } else if($1 == "Domain" && w == 1) {
        p = $2 "/" p
        w = 2
      } else if($1 == "Password" && w == 2) {
        print p ":" $2
      } else {
        w = 0
      }
    }' | sort -u