#!/bin/bash

if [ "$#" -ne 1 ]; then
  printf '%s\n' 'usage: '"$0"' <sekurlsa::logonpasswords file>'
  exit 0
fi

cat "$1" | grep -E '\* (Username|Domain|NTLM|Password)' | sed 's/^ *\* //; s/ *: */:/' | \
  awk -F: '
    function err(expe, but) {
      print "error: expected", expe, "but", but, "exist" > "/dev/stderr"
      exit
    }
    {
      if($2 == "(null)") {
        w = 0
      } else if(NR % 3 == 1) {
        cur = "Username"
        if($1 == cur) {
          if($2 ~ /.*\$$/) {
            w = 0
          } else {
            p = $2
            w = 1
          }
        } else {
          err(cur, $1)
        }
      } else if(NR % 3 == 2) {
        cur = "Domain"
        if($1 == cur) {
          p = $2 "/" p
        } else {
          err(cur, $1)
        }
      } else if(($1 == "NTLM" || $1 == "Password")) {
        if (w == 1 && $1 == "NTLM") {
          print p ":" $2
        }
      } else {
        err("NTLM or Password", $1)
      }
    }' | sort -u